### ISSUE TITLE
Implement a services catalog

### ISSUE THREAD

**Issue by dcharbon** [openteamsinc/scrud-django#4]
This catalog should include a single way to register an endpoint that maps the RDF type URI of the resource to the URL for that resource. For example:

```json
{
    "https://api.openteams.com/json-ld/PartnerProfile-Listing":
        "https://backend.openteams.com/partner-profiles"
    , ...
}
```

The example above shows a services catalog resource that includes an entry for the listing of partner profile resources.

We'll also need json-ld and schema for the services catalog resource itself... That is, this endpoint will also be a [semantic resource](https://openteamsinc.github.io/semantic-http-spec/semantic_http_resource.html)

**Comment by dcharbon** [comment]
I've added some documentation [here](https://openteamsinc.github.io/openteams-scrud-strategy/service-catalog.html). The JSON-LD pattern is taken from the [spec for data indexing](https://www.w3.org/TR/json-ld/#data-indexing).

**Comment by trentoliphant** [comment]
Done for now - needs to be refactored when #23 is completed
